<Project>
  <PropertyGroup><ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally></PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="11.3.13" />
    <PackageVersion Include="Avalonia.Desktop" Version="11.3.13" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="11.3.13" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="11.3.13" />
    <PackageVersion Include="Avalonia.Headless.XUnit" Version="11.3.13" />
    <PackageVersion Include="AvaloniaSkinManager" Version="2.0.1" />
    <PackageVersion Include="Avalonia.AvaloniaEdit" Version="11.4.1" />
    <PackageVersion Include="Markdig" Version="1.3.2" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.1" />
  <PackageVersion Include="Tmds.DBus.Protocol" Version="0.21.3" /></ItemGroup>
</Project>
